'use client';

import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@supabase/supabase-js';

const URL=process.env.NEXT_PUBLIC_SUPABASE_URL,KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const domainNames={reasoning:'الاستدلال',math:'الرياضيات',science:'العلوم',coding:'البرمجة',language:'اللغة',research:'البحث',planning:'التخطيط',general:'عام'};

function Ring({value=0}){const v=Math.max(0,Math.min(100,Number(value)||0));return <div className="ring" style={{'--p':`${v*3.6}deg`}}><div><strong>{v.toFixed(0)}</strong><span>/100</span></div></div>}
function Metric({label,value,sub}){return <div className="metric-card"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}

export default function AdminPage(){
  const sb=useMemo(()=>URL&&KEY?createClient(URL,KEY):null,[]);
  const [ready,setReady]=useState(false),[session,setSession]=useState(null),[tab,setTab]=useState('overview'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [status,setStatus]=useState(null),[settings,setSettings]=useState(null),[skills,setSkills]=useState([]),[runs,setRuns]=useState([]),[goal,setGoal]=useState(null),[lessons,setLessons]=useState([]),[memories,setMemories]=useState([]),[examples,setExamples]=useState([]),[profiles,setProfiles]=useState([]),[counts,setCounts]=useState({});

  useEffect(()=>{if(!sb){setReady(true);return}sb.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)});const{data}=sb.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[sb]);
  useEffect(()=>{if(session)loadAll()},[session]);

  async function ensureSettings(){const u=(await sb.auth.getUser()).data.user;if(!u)return null;let {data}=await sb.from('control_settings').select('*').eq('owner_id',u.id).maybeSingle();if(!data){const r=await sb.from('control_settings').insert({owner_id:u.id}).select('*').single();data=r.data}setSettings(data);return data}
  async function loadAll(){setBusy(true);try{const [st,sk,gr,go,le,me,ex,pr]=await Promise.all([fetch('/api/status',{headers:{Authorization:`Bearer ${session.access_token}`}}).then(r=>r.json()),sb.from('skill_state').select('*').order('score',{ascending:true}),sb.from('goal_runs').select('*').order('created_at',{ascending:false}).limit(20),sb.from('goals').select('*').eq('status','active').order('priority',{ascending:false}).limit(1),sb.from('lessons').select('id,title,instruction,category,status,priority,created_at').order('created_at',{ascending:false}).limit(40),sb.from('memories').select('id,content,enabled,created_at').order('created_at',{ascending:false}).limit(60),sb.from('training_examples').select('id,user_input,preferred_answer,assistant_bad_answer,category,quality_status,tags,created_at').order('created_at',{ascending:false}).limit(80),sb.from('model_profiles').select('*').order('created_at',{ascending:false})]);setStatus(st);setSkills(sk.data||[]);setRuns(gr.data||[]);setGoal(go.data?.[0]||null);setLessons(le.data||[]);setMemories(me.data||[]);setExamples(ex.data||[]);setProfiles(pr.data||[]);const s=await ensureSettings();if(s)setSettings(s);setCounts({lessons:(le.data||[]).length,memories:(me.data||[]).length,candidates:(ex.data||[]).filter(x=>x.quality_status==='candidate').length,approved:(ex.data||[]).filter(x=>x.quality_status==='approved').length})}finally{setBusy(false)}}
  async function saveSettings(){if(!settings)return;setNotice('');const {owner_id,created_at,updated_at,...patch}=settings;const {error}=await sb.from('control_settings').update(patch).eq('owner_id',owner_id);setNotice(error?error.message:'تم حفظ إعدادات MUS AI.');if(!error)loadAll()}
  async function runGoal(){setBusy(true);setNotice('');try{const r=await fetch('/api/goal/run',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:'{}'}),d=await r.json();if(!r.ok)throw Error(d.message||'فشلت الدورة.');setNotice(`اكتملت دورة ${d.domain}: ${d.score}/100`);await loadAll()}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  async function rateExample(id,status){const {error}=await sb.from('training_examples').update({quality_status:status}).eq('id',id);if(error)setNotice(error.message);else loadAll()}
  async function addMemory(){const content=prompt('اكتب المعلومة التي تريد إضافتها إلى ذاكرة MUS AI:')?.trim();if(!content)return;const u=(await sb.auth.getUser()).data.user;const{error}=await sb.from('memories').insert({owner_id:u.id,content,enabled:true});if(error)setNotice(error.message);else loadAll()}
  async function toggleMemory(id,enabled){await sb.from('memories').update({enabled}).eq('id',id);loadAll()}
  async function addLesson(){const text=prompt('اكتب الدرس أو القاعدة التي تريد تعليمها لـ MUS AI:')?.trim();if(!text)return;const u=(await sb.auth.getUser()).data.user;const{error}=await sb.from('lessons').insert({owner_id:u.id,title:text.slice(0,70),instruction:text,category:'general',scope:'global',priority:70,status:'approved'});if(error)setNotice(error.message);else loadAll()}

  if(!ready)return <div className="center-screen">جاري التحميل…</div>;
  if(!session)return <div className="center-screen"><div className="error-box">يجب تسجيل الدخول أولًا من <a href="/">تطبيق MUS AI</a>.</div></div>;
  const avg=skills.length?skills.reduce((a,x)=>a+Number(x.score||0),0)/skills.length:0;
  const nav=[['overview','نظرة عامة'],['model','النموذج والمحرك'],['learning','التعلم والتقييم'],['data','بيانات التدريب'],['memory','الذاكرة والدروس'],['settings','الإعدادات']];
  return <div className="admin-shell" dir="rtl"><aside className="admin-sidebar"><div className="brand-lockup compact"><div className="brand-mark">M</div><div><strong>MUS AI</strong><span>Control Center</span></div></div><div className="admin-nav">{nav.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div><div className="admin-side-footer"><a href="/">← العودة إلى الشات</a><span>Research Build</span></div></aside><main className="admin-main"><header className="admin-header"><div><span className="eyebrow">MUS AI CONTROL CENTER</span><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1></div><div className="header-actions"><span className={`health-pill ${status?.openrouter_configured?'ok':'warn'}`}><i/>{status?.openrouter_configured?'النظام متصل':'يحتاج إعداد'}</span><button className="refresh-btn" onClick={loadAll} disabled={busy}>تحديث</button></div></header>{notice&&<div className="admin-notice">{notice}</div>}

  {tab==='overview'&&<><section className="hero-card"><div><span className="eyebrow">NORTH STAR</span><h2>{goal?.name||'MUS AI North Star'}</h2><p>{goal?.objective||'تطوير MUS AI ليحقق أعلى قدرة موثوقة بأقل تكلفة، مع قياس التحسن قبل اعتماد أي نسخة.'}</p><div className="hero-tags"><span>OpenRouter الآن</span><span>النموذج الذاتي لاحقًا</span><span>لا ادعاء بلا Benchmark</span></div></div><Ring value={avg}/></section><section className="metric-grid"><Metric label="متوسط القوة" value={`${avg.toFixed(0)}/100`} sub={`${skills.length} مجالات مراقبة`}/><Metric label="أمثلة معتمدة" value={counts.approved||0} sub="جاهزة للداتا سيت"/><Metric label="مرشحو تدريب" value={counts.candidates||0} sub="بانتظار المراجعة"/><Metric label="دورات تعلم" value={runs.length} sub="آخر 20 دورة"/></section><section className="panel-grid"><div className="admin-panel"><div className="panel-head"><div><span className="eyebrow">RUNTIME</span><h3>حالة المحرك</h3></div><span className="state-badge">{settings?.runtime_mode||'openrouter_primary'}</span></div><div className="status-list"><div><span>OpenRouter</span><b>{status?.openrouter_configured?'متصل':'غير متصل'}</b></div><div><span>MUS Self-hosted</span><b>{status?.self_hosted_configured?'متصل':'لم يُربط بعد'}</b></div><div><span>النموذج النشط</span><b>{settings?.openrouter_model||'openrouter/free'}</b></div><div><span>ميزانية يومية</span><b>${Number(settings?.daily_budget_usd||0).toFixed(2)}</b></div></div></div><div className="admin-panel"><div className="panel-head"><div><span className="eyebrow">SKILLS</span><h3>أضعف المجالات الآن</h3></div></div><div className="skill-stack">{skills.slice(0,6).map(s=><div className="skill-line" key={s.domain}><div><span>{domainNames[s.domain]||s.domain}</span><b>{Number(s.score||0).toFixed(0)}</b></div><div><i style={{width:`${Math.max(2,Number(s.score)||0)}%`}}/></div></div>)}</div></div></section></>}

  {tab==='model'&&<><section className="admin-panel wide"><div className="panel-head"><div><span className="eyebrow">ROUTING</span><h3>المحرك والمزود</h3><p>OpenRouter هو المحرك الأساسي الآن. عندما يصبح نموذج MUS AI موثوقًا يمكنك تحويل المسار من هنا دون إعادة بناء الواجهة.</p></div></div>{settings&&<div className="form-grid"><label>أولوية التشغيل<select value={settings.runtime_mode} onChange={e=>setSettings({...settings,runtime_mode:e.target.value})}><option value="openrouter_primary">OpenRouter أولًا ثم MUS</option><option value="openrouter_only">OpenRouter فقط</option><option value="self_hosted_primary">MUS أولًا ثم OpenRouter</option><option value="self_hosted_only">MUS فقط</option></select></label><label>نموذج OpenRouter<input value={settings.openrouter_model||''} onChange={e=>setSettings({...settings,openrouter_model:e.target.value})} placeholder="openrouter/free"/></label><label>Temperature<input type="number" min="0" max="2" step="0.1" value={settings.temperature??0.6} onChange={e=>setSettings({...settings,temperature:Number(e.target.value)})}/></label><label>سياق المحادثة<input type="number" min="4" max="64" value={settings.max_history||16} onChange={e=>setSettings({...settings,max_history:Number(e.target.value)})}/></label></div>}<div className="control-row"><label className="switch-row"><input type="checkbox" checked={!!settings?.web_search_default} onChange={e=>setSettings({...settings,web_search_default:e.target.checked})}/><span><b>بحث الويب افتراضيًا</b><small>يجعل MUS AI يستخدم البحث عندما يكون مفيدًا</small></span></label><label className="switch-row"><input type="checkbox" checked={!!settings?.save_training_candidates} onChange={e=>setSettings({...settings,save_training_candidates:e.target.checked})}/><span><b>حفظ أمثلة التدريب</b><small>كل محادثة مفيدة تصبح مرشحًا للتعلم</small></span></label></div><button className="primary-btn fit" onClick={saveSettings}>حفظ إعدادات النموذج</button></section><section className="admin-panel wide"><div className="panel-head"><div><span className="eyebrow">MODEL REGISTRY</span><h3>إصدارات MUS AI</h3></div></div><div className="table-list">{profiles.length?profiles.map(p=><div className="table-row" key={p.id}><div><b>{p.name}</b><span>{p.base_model}</span></div><span className={p.is_default?'green-text':''}>{p.is_default?'Default':'Standby'}</span><span>{p.evaluation_score??'—'}</span></div>):<div className="empty-panel">لا توجد إصدارات مسجلة بعد.</div>}</div></section></>}

  {tab==='learning'&&<><section className="section-title-row"><div><span className="eyebrow">AUTONOMOUS IMPROVEMENT</span><h2>التعلم والتقييم</h2><p>اختر أضعف نقطة، اختبرها، احفظ النتيجة الموثوقة فقط.</p></div><button className="primary-btn fit" onClick={runGoal} disabled={busy}>نفّذ دورة تعلم الآن</button></section><div className="skill-cards">{skills.map(s=><div className="skill-card" key={s.domain}><div className="skill-card-head"><div><span>{domainNames[s.domain]||s.domain}</span><small>{s.attempts||0} محاولات · {s.wins||0} نجاح</small></div><strong>{Number(s.score||0).toFixed(0)}</strong></div><div className="skill-meter"><i style={{width:`${Math.max(2,Number(s.score)||0)}%`}}/></div></div>)}</div><section className="admin-panel wide"><div className="panel-head"><h3>آخر دورات التعلم</h3></div><div className="table-list">{runs.map(r=><div className="table-row" key={r.id}><div><b>{domainNames[r.domain]||r.domain}</b><span>{new Date(r.created_at).toLocaleString('ar-MA')}</span></div><span>{r.provider||'—'}</span><strong>{Number(r.score||0).toFixed(0)}/100</strong><span>${Number(r.cost_usd||0).toFixed(4)}</span></div>)}</div></section></>}

  {tab==='data'&&<><section className="section-title-row"><div><span className="eyebrow">TRAINING DATA</span><h2>بيانات التدريب</h2><p>لا يدخل المثال إلى الداتا سيت المعتمد إلا بعد المراجعة.</p></div><div className="data-summary"><span>{counts.approved||0} معتمد</span><span>{counts.candidates||0} مرشح</span></div></section><section className="admin-panel wide"><div className="training-list">{examples.length?examples.map(x=><div className="training-item" key={x.id}><div className="training-top"><span className={`quality ${x.quality_status}`}>{x.quality_status}</span><small>{new Date(x.created_at).toLocaleDateString('ar-MA')}</small></div><b>{x.user_input}</b><p>{(x.preferred_answer||x.assistant_bad_answer||'').slice(0,360)}</p>{x.quality_status==='candidate'&&<div className="review-actions"><button onClick={()=>rateExample(x.id,'approved')}>اعتماد</button><button className="danger-btn" onClick={()=>rateExample(x.id,'rejected')}>رفض</button></div>}</div>):<div className="empty-panel">لا توجد أمثلة بعد.</div>}</div></section></>}

  {tab==='memory'&&<div className="memory-columns"><section className="admin-panel"><div className="panel-head"><div><span className="eyebrow">MEMORY</span><h3>الذاكرة الدائمة</h3></div><button className="ghost-fit" onClick={addMemory}>+ إضافة</button></div><div className="memory-list">{memories.map(m=><div className="memory-item" key={m.id}><p>{m.content}</p><label><input type="checkbox" checked={!!m.enabled} onChange={e=>toggleMemory(m.id,e.target.checked)}/> نشطة</label></div>)}</div></section><section className="admin-panel"><div className="panel-head"><div><span className="eyebrow">BEHAVIOR</span><h3>الدروس والقواعد</h3></div><button className="ghost-fit" onClick={addLesson}>+ درس</button></div><div className="memory-list">{lessons.map(l=><div className="memory-item" key={l.id}><div className="lesson-meta"><span>{l.category}</span><span>P{l.priority}</span></div><b>{l.title}</b><p>{l.instruction}</p></div>)}</div></section></div>}

  {tab==='settings'&&settings&&<section className="admin-panel wide"><div className="panel-head"><div><span className="eyebrow">COST & SAFETY</span><h3>الميزانية والصلاحيات</h3><p>هذه الإعدادات تمنع MUS AI من التحول إلى نظام مكلف دون قرار منك.</p></div></div><div className="form-grid"><label>الحد اليومي بالدولار<input type="number" min="0" step="0.1" value={settings.daily_budget_usd||0} onChange={e=>setSettings({...settings,daily_budget_usd:Number(e.target.value)})}/></label><label>ملاحظة النظام<textarea rows="4" value={settings.system_note||''} onChange={e=>setSettings({...settings,system_note:e.target.value})} placeholder="تعليمات إضافية خاصة بـ MUS AI..."/></label></div><div className="control-row"><label className="switch-row"><input type="checkbox" checked={!!settings.auto_learning} onChange={e=>setSettings({...settings,auto_learning:e.target.checked})}/><span><b>التعلم التلقائي</b><small>يسمح بحلقات التعلم المجدولة</small></span></label><label className="switch-row"><input type="checkbox" checked={!!settings.allow_paid_external} onChange={e=>setSettings({...settings,allow_paid_external:e.target.checked})}/><span><b>السماح بنماذج OpenRouter المدفوعة</b><small>مغلق افتراضيًا لحماية الرصيد</small></span></label><label className="switch-row"><input type="checkbox" checked={!!settings.allow_paid_gpu} onChange={e=>setSettings({...settings,allow_paid_gpu:e.target.checked})}/><span><b>السماح بـ GPU مدفوع</b><small>لا يبدأ أي GPU مدفوع تلقائيًا ما دام هذا الخيار مغلقًا</small></span></label></div><button className="primary-btn fit" onClick={saveSettings}>حفظ الإعدادات</button></section>}
  </main></div>
}
