'use client';

import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@supabase/supabase-js';

const URL=process.env.NEXT_PUBLIC_SUPABASE_URL,KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const domainNames={reasoning:'الاستدلال',math:'الرياضيات',science:'العلوم',coding:'البرمجة',language:'اللغة',research:'البحث',planning:'التخطيط',general:'عام'};
function Metric({label,value,sub}){return <div className="metric-card"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function Ring({value=0}){const v=Math.max(0,Math.min(100,Number(value)||0));return <div className="ring" style={{'--p':`${v*3.6}deg`}}><div><strong>{v.toFixed(0)}</strong><span>/100</span></div></div>}

export default function AdminPage(){
  const sb=useMemo(()=>URL&&KEY?createClient(URL,KEY):null,[]);
  const [ready,setReady]=useState(false),[session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authMsg,setAuthMsg]=useState('');
  const [tab,setTab]=useState('overview'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState(null),[settings,setSettings]=useState(null);
  const [skills,setSkills]=useState([]),[runs,setRuns]=useState([]),[goal,setGoal]=useState(null),[lessons,setLessons]=useState([]),[memories,setMemories]=useState([]),[examples,setExamples]=useState([]),[profiles,setProfiles]=useState([]),[versions,setVersions]=useState([]),[evaluations,setEvaluations]=useState([]),[publicLogs,setPublicLogs]=useState([]),[publicFeedback,setPublicFeedback]=useState([]),[toolRuns,setToolRuns]=useState([]),[approvals,setApprovals]=useState([]),[audit,setAudit]=useState([]),[counts,setCounts]=useState({});

  useEffect(()=>{if(!sb){setReady(true);return}sb.auth.getSession().then(({data})=>{setSession(data.session||null);setReady(true)});const{data}=sb.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[sb]);
  useEffect(()=>{if(session)loadAll()},[session]);

  async function login(e){e.preventDefault();setAuthMsg('');const r=await sb.auth.signInWithPassword({email,password});if(r.error)setAuthMsg(r.error.message?.toLowerCase().includes('invalid login')?'بيانات الدخول غير صحيحة.':r.error.message)}
  async function ensureSettings(){const u=(await sb.auth.getUser()).data.user;if(!u)return null;let {data}=await sb.from('control_settings').select('*').eq('owner_id',u.id).maybeSingle();if(!data){const r=await sb.from('control_settings').insert({owner_id:u.id}).select('*').single();data=r.data}setSettings(data);return data}
  async function loadAll(){
    setBusy(true);setNotice('');
    try{
      const q=await Promise.all([
        fetch('/api/status',{cache:'no-store'}).then(r=>r.json()),
        sb.from('skill_state').select('*').order('score',{ascending:true}),
        sb.from('goal_runs').select('*').order('created_at',{ascending:false}).limit(30),
        sb.from('goals').select('*').eq('status','active').order('priority',{ascending:false}).limit(1),
        sb.from('lessons').select('id,title,instruction,category,status,priority,created_at').order('created_at',{ascending:false}).limit(80),
        sb.from('memories').select('id,content,enabled,created_at').order('created_at',{ascending:false}).limit(100),
        sb.from('training_examples').select('id,user_input,preferred_answer,assistant_bad_answer,category,quality_status,tags,context_snapshot,created_at').order('created_at',{ascending:false}).limit(150),
        sb.from('model_profiles').select('*').order('created_at',{ascending:false}),
        sb.from('model_versions').select('*').order('created_at',{ascending:false}).limit(30),
        sb.from('evaluations').select('*').order('created_at',{ascending:false}).limit(30),
        sb.from('public_chat_logs').select('*').order('created_at',{ascending:false}).limit(300),
        sb.from('public_feedback').select('*').order('created_at',{ascending:false}).limit(300),
        sb.from('tool_runs').select('*').order('created_at',{ascending:false}).limit(40),
        sb.from('approvals').select('*').order('created_at',{ascending:false}).limit(40),
        sb.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(60)
      ]);
      const [st,sk,gr,go,le,me,ex,pr,mv,ev,pl,pf,tr,ap,au]=q;
      setStatus(st);setSkills(sk.data||[]);setRuns(gr.data||[]);setGoal(go.data?.[0]||null);setLessons(le.data||[]);setMemories(me.data||[]);setExamples(ex.data||[]);setProfiles(pr.data||[]);setVersions(mv.data||[]);setEvaluations(ev.data||[]);setPublicLogs(pl.data||[]);setPublicFeedback(pf.data||[]);setToolRuns(tr.data||[]);setApprovals(ap.data||[]);setAudit(au.data||[]);
      const s=await ensureSettings();if(s)setSettings(s);
      const sessions=new Set((pl.data||[]).map(x=>x.session_id)).size,good=(pf.data||[]).filter(x=>x.rating==='good').length,bad=(pf.data||[]).filter(x=>x.rating==='bad').length;
      setCounts({lessons:(le.data||[]).length,memories:(me.data||[]).length,candidates:(ex.data||[]).filter(x=>x.quality_status==='candidate').length,approved:(ex.data||[]).filter(x=>x.quality_status==='approved').length,publicChats:(pl.data||[]).length,sessions,good,bad});
    }catch(e){setNotice(e.message||'تعذر تحميل لوحة التحكم.')}finally{setBusy(false)}
  }
  async function saveSettings(){if(!settings)return;setNotice('');const {owner_id,created_at,updated_at,...patch}=settings;const {error}=await sb.from('control_settings').update(patch).eq('owner_id',owner_id);setNotice(error?error.message:'تم حفظ إعدادات MUS AI.');if(!error)loadAll()}
  async function runGoal(){setBusy(true);setNotice('');try{const r=await fetch('/api/goal/run',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:'{}'}),d=await r.json();if(!r.ok)throw Error(d.message||'فشلت الدورة.');setNotice(`اكتملت دورة ${domainNames[d.domain]||d.domain}: ${d.score}/100`);await loadAll()}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  async function rateExample(id,statusValue){const {error}=await sb.from('training_examples').update({quality_status:statusValue}).eq('id',id);if(error)setNotice(error.message);else loadAll()}
  async function addMemory(){const content=prompt('اكتب المعلومة التي تريد إضافتها إلى ذاكرة MUS AI:')?.trim();if(!content)return;const u=(await sb.auth.getUser()).data.user;const{error}=await sb.from('memories').insert({owner_id:u.id,content,enabled:true});if(error)setNotice(error.message);else loadAll()}
  async function toggleMemory(id,enabled){await sb.from('memories').update({enabled}).eq('id',id);loadAll()}
  async function addLesson(){const text=prompt('اكتب الدرس أو القاعدة الجديدة:')?.trim();if(!text)return;const u=(await sb.auth.getUser()).data.user;const{error}=await sb.from('lessons').insert({owner_id:u.id,title:text.slice(0,70),instruction:text,category:'general',scope:'global',priority:70,status:'approved'});if(error)setNotice(error.message);else loadAll()}

  if(!URL||!KEY)return <div className="center-screen"><div className="error-box">إعداد Supabase غير مكتمل.</div></div>;
  if(!ready)return <div className="center-screen"><div className="brand-loader"><img src="/api/status?icon=1" alt=""/><b>MUS AI</b></div></div>;
  if(!session)return <div className="admin-login-shell"><form className="admin-login-card" onSubmit={login}><img src="/api/status?icon=1" alt="MUS AI"/><span className="eyebrow">PRIVATE CONTROL CENTER</span><h1>MUS AI</h1><p>لوحة الإدارة الخاصة بالمشروع. لا تظهر للمستخدمين.</p><label>البريد الإلكتروني<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>كلمة المرور<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary-btn" type="submit">دخول لوحة التحكم</button>{authMsg&&<div className="auth-msg">{authMsg}</div>}</form></div>;

  const avg=skills.length?skills.reduce((a,x)=>a+Number(x.score||0),0)/skills.length:0;
  const nav=[['overview','نظرة عامة'],['model','النموذج والمحرك'],['learning','التعلم والتقييم'],['data','بيانات التدريب'],['users','المستخدمون والتطبيق'],['memory','الذاكرة والدروس'],['safety','الأمان والسجل'],['settings','الإعدادات']];
  const feedbackTotal=(counts.good||0)+(counts.bad||0),positive=feedbackTotal?Math.round((counts.good/feedbackTotal)*100):0;

  return <div className="admin-shell" dir="rtl"><aside className="admin-sidebar"><div className="brand-lockup compact admin-brand"><img className="brand-icon" src="/api/status?icon=1" alt="MUS AI"/><div><strong>MUS AI</strong><span>CONTROL CENTER</span></div></div><div className="admin-nav">{nav.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div><div className="admin-side-footer"><a href="/" target="_blank">فتح تطبيق MUS AI ↗</a><button onClick={()=>sb.auth.signOut()}>تسجيل الخروج</button><span>Private Admin</span></div></aside>
  <main className="admin-main"><header className="admin-header"><div><span className="eyebrow">MUS AI CONTROL CENTER</span><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1></div><div className="header-actions"><span className={`health-pill ${status?.openrouter_configured||status?.self_hosted_configured?'ok':'warn'}`}><i/>{status?.openrouter_configured||status?.self_hosted_configured?'النظام متصل':'يحتاج إعداد'}</span><button className="refresh-btn" onClick={loadAll} disabled={busy}>{busy?'…':'تحديث'}</button></div></header>{notice&&<div className="admin-notice">{notice}</div>}

  {tab==='overview'&&<><section className="hero-card"><div><span className="eyebrow">NORTH STAR</span><h2>{goal?.name||'MUS AI North Star'}</h2><p>{goal?.objective||'تطوير MUS AI ليحقق أعلى قدرة موثوقة بأقل تكلفة مع قياس التحسن باستمرار.'}</p><div className="hero-tags"><span>OpenRouter الآن</span><span>MUS Engine لاحقًا</span><span>Benchmark قبل الثقة</span></div></div><Ring value={avg}/></section><section className="metric-grid"><Metric label="متوسط القوة" value={`${avg.toFixed(0)}/100`} sub={`${skills.length} مجالات`}/><Metric label="جلسات عامة" value={counts.sessions||0} sub="ضمن آخر 300 محادثة"/><Metric label="أمثلة معتمدة" value={counts.approved||0} sub="جاهزة للداتا سيت"/><Metric label="رضا المستخدمين" value={`${positive}%`} sub={`${feedbackTotal} تقييمات`}/></section><section className="panel-grid"><div className="admin-panel"><div className="panel-head"><div><span className="eyebrow">RUNTIME</span><h3>حالة المحرك</h3></div><span className="state-badge">{settings?.runtime_mode||'openrouter_primary'}</span></div><div className="status-list"><div><span>OpenRouter</span><b>{status?.openrouter_configured?'متصل':'غير متصل'}</b></div><div><span>MUS Self-hosted</span><b>{status?.self_hosted_configured?'متصل':'غير متصل'}</b></div><div><span>النموذج</span><b>{settings?.openrouter_model||'openrouter/free'}</b></div><div><span>المحادثة العامة</span><b>{settings?.public_chat_enabled?'مفتوحة':'موقوفة'}</b></div></div></div><div className="admin-panel"><div className="panel-head"><div><span className="eyebrow">WEAKEST SKILLS</span><h3>أضعف المجالات</h3></div></div><div className="skill-stack">{skills.slice(0,6).map(s=><div className="skill-line" key={s.domain}><div><span>{domainNames[s.domain]||s.domain}</span><b>{Number(s.score||0).toFixed(0)}</b></div><div><i style={{width:`${Math.max(2,Number(s.score)||0)}%`}}/></div></div>)}</div></div></section></>}

  {tab==='model'&&<><section className="admin-panel wide"><div className="panel-head"><div><span className="eyebrow">ROUTING</span><h3>المحرك والمزود</h3><p>غيّر مسار التشغيل من هنا دون تغيير تطبيق المستخدم.</p></div></div>{settings&&<div className="form-grid"><label>أولوية التشغيل<select value={settings.runtime_mode} onChange={e=>setSettings({...settings,runtime_mode:e.target.value})}><option value="openrouter_primary">OpenRouter أولًا ثم MUS</option><option value="openrouter_only">OpenRouter فقط</option><option value="self_hosted_primary">MUS أولًا ثم OpenRouter</option><option value="self_hosted_only">MUS فقط</option></select></label><label>نموذج OpenRouter<input value={settings.openrouter_model||''} onChange={e=>setSettings({...settings,openrouter_model:e.target.value})}/></label><label>Temperature<input type="number" min="0" max="2" step="0.1" value={settings.temperature??0.6} onChange={e=>setSettings({...settings,temperature:Number(e.target.value)})}/></label><label>سياق المحادثة<input type="number" min="4" max="64" value={settings.max_history||16} onChange={e=>setSettings({...settings,max_history:Number(e.target.value)})}/></label></div>}<button className="primary-btn fit" onClick={saveSettings}>حفظ إعدادات المحرك</button></section><section className="panel-grid"><div className="admin-panel"><div className="panel-head"><h3>سجل النماذج</h3></div><div className="table-list">{profiles.length?profiles.map(p=><div className="table-row" key={p.id}><div><b>{p.name}</b><span>{p.base_model}</span></div><span>{p.is_default?'Default':'Standby'}</span><strong>{p.evaluation_score??'—'}</strong></div>):<div className="empty-panel">لا توجد نماذج مسجلة.</div>}</div></div><div className="admin-panel"><div className="panel-head"><h3>الإصدارات والتقييمات</h3></div><div className="mini-timeline">{versions.slice(0,8).map(v=><div key={v.id}><b>{v.version}</b><span>{new Date(v.created_at).toLocaleDateString('ar-MA')}</span></div>)}{evaluations.slice(0,6).map(e=><div key={e.id}><b>Evaluation {e.score??'—'}</b><span>{e.promoted?'Promoted':'Measured'}</span></div>)}</div></div></section></>}

  {tab==='learning'&&<><section className="section-title-row"><div><span className="eyebrow">AUTONOMOUS IMPROVEMENT</span><h2>التعلم والتقييم</h2><p>اختبار → تحقق → حفظ المثال → تحديث خريطة القوة.</p></div><button className="primary-btn fit" onClick={runGoal} disabled={busy}>نفّذ دورة تعلم الآن</button></section><div className="skill-cards">{skills.map(s=><div className="skill-card" key={s.domain}><div className="skill-card-head"><div><span>{domainNames[s.domain]||s.domain}</span><small>{s.attempts||0} محاولات · {s.wins||0} نجاح</small></div><strong>{Number(s.score||0).toFixed(0)}</strong></div><div className="skill-meter"><i style={{width:`${Math.max(2,Number(s.score)||0)}%`}}/></div></div>)}</div><section className="admin-panel wide"><div className="panel-head"><h3>آخر دورات التعلم</h3></div><div className="table-list">{runs.map(r=><div className="table-row" key={r.id}><div><b>{domainNames[r.domain]||r.domain}</b><span>{new Date(r.created_at).toLocaleString('ar-MA')}</span></div><span>{r.provider||'—'}</span><strong>{Number(r.score||0).toFixed(0)}/100</strong><span>${Number(r.cost_usd||0).toFixed(4)}</span></div>)}</div></section></>}

  {tab==='data'&&<><section className="section-title-row"><div><span className="eyebrow">TRAINING DATA</span><h2>بيانات التدريب</h2><p>محادثات المستخدمين تدخل كمرشحين فقط، ولا تُعتمد إلا بعد المراجعة.</p></div><div className="data-summary"><span>{counts.approved||0} معتمد</span><span>{counts.candidates||0} مرشح</span></div></section><section className="admin-panel wide"><div className="training-list">{examples.length?examples.map(x=><div className="training-item" key={x.id}><div className="training-top"><span className={`quality ${x.quality_status}`}>{x.quality_status}</span><small>{new Date(x.created_at).toLocaleDateString('ar-MA')}</small></div><b>{x.user_input}</b><p>{(x.preferred_answer||x.assistant_bad_answer||'').slice(0,430)}</p>{x.context_snapshot?.source==='public-chat'&&<span className="source-chip">Public chat</span>}{x.quality_status==='candidate'&&<div className="review-actions"><button onClick={()=>rateExample(x.id,'approved')}>اعتماد</button><button className="danger-btn" onClick={()=>rateExample(x.id,'rejected')}>رفض</button></div>}</div>):<div className="empty-panel">لا توجد أمثلة بعد.</div>}</div></section></>}

  {tab==='users'&&<><section className="metric-grid"><Metric label="جلسات مجهولة" value={counts.sessions||0} sub="لا نطلب حسابًا"/><Metric label="محادثات محفوظة" value={counts.publicChats||0} sub="آخر 300 سجل"/><Metric label="تقييمات جيدة" value={counts.good||0}/><Metric label="تقييمات ضعيفة" value={counts.bad||0}/></section><section className="panel-grid"><div className="admin-panel"><div className="panel-head"><div><span className="eyebrow">PUBLIC APP</span><h3>تطبيق المستخدمين</h3></div></div><div className="status-list"><div><span>بدون تسجيل دخول</span><b>نعم</b></div><div><span>قابل للتثبيت PWA</span><b>{settings?.install_enabled?'نعم':'موقوف'}</b></div><div><span>حفظ للتدريب</span><b>{settings?.public_training_enabled?'مفعّل':'موقوف'}</b></div><div><span>حد الساعة</span><b>{settings?.public_rate_limit_per_hour||30}</b></div></div><a className="primary-btn fit inline-link" href="/" target="_blank">فتح التطبيق العام</a></div><div className="admin-panel"><div className="panel-head"><h3>أحدث المحادثات</h3></div><div className="public-log-list">{publicLogs.slice(0,20).map(x=><div className="public-log" key={x.id}><b>{x.user_input.slice(0,120)}</b><p>{x.assistant_output.slice(0,220)}</p><span>{x.model||x.provider||'MUS AI'} · {new Date(x.created_at).toLocaleString('ar-MA')}</span></div>)}</div></div></section></>}

  {tab==='memory'&&<div className="memory-columns"><section className="admin-panel"><div className="panel-head"><div><span className="eyebrow">MEMORY</span><h3>الذاكرة الدائمة</h3></div><button className="ghost-fit" onClick={addMemory}>+ إضافة</button></div><div className="memory-list">{memories.map(m=><div className="memory-item" key={m.id}><p>{m.content}</p><label><input type="checkbox" checked={!!m.enabled} onChange={e=>toggleMemory(m.id,e.target.checked)}/> نشطة</label></div>)}</div></section><section className="admin-panel"><div className="panel-head"><div><span className="eyebrow">BEHAVIOR</span><h3>الدروس والقواعد</h3></div><button className="ghost-fit" onClick={addLesson}>+ درس</button></div><div className="memory-list">{lessons.map(l=><div className="memory-item" key={l.id}><div className="lesson-meta"><span>{l.category}</span><span>P{l.priority}</span></div><b>{l.title}</b><p>{l.instruction}</p></div>)}</div></section></div>}

  {tab==='safety'&&<><section className="metric-grid"><Metric label="أدوات منفذة" value={toolRuns.length}/><Metric label="طلبات موافقة" value={approvals.length}/><Metric label="سجل تدقيق" value={audit.length}/><Metric label="مدفوع تلقائي" value={settings?.allow_paid_external||settings?.allow_paid_gpu?'مسموح':'مغلق'}/></section><section className="panel-grid"><div className="admin-panel"><div className="panel-head"><h3>Tool Runs</h3></div><div className="table-list compact-table">{toolRuns.length?toolRuns.map(x=><div className="table-row" key={x.id}><div><b>{x.tool_name}</b><span>{x.risk_level}</span></div><span>{x.status}</span></div>):<div className="empty-panel">لا توجد عمليات أدوات.</div>}</div></div><div className="admin-panel"><div className="panel-head"><h3>Audit Log</h3></div><div className="table-list compact-table">{audit.length?audit.map(x=><div className="table-row" key={x.id}><div><b>{x.action}</b><span>{x.entity_type||'system'}</span></div><span>{new Date(x.created_at).toLocaleString('ar-MA')}</span></div>):<div className="empty-panel">لا توجد أحداث تدقيق.</div>}</div></div></section></>}

  {tab==='settings'&&settings&&<section className="admin-panel wide"><div className="panel-head"><div><span className="eyebrow">SYSTEM CONTROL</span><h3>الإعدادات والميزانية</h3><p>كل ما يؤثر على المستخدمين أو التكلفة يُضبط من هنا.</p></div></div><div className="form-grid"><label>الحد اليومي بالدولار<input type="number" min="0" step="0.1" value={settings.daily_budget_usd||0} onChange={e=>setSettings({...settings,daily_budget_usd:Number(e.target.value)})}/></label><label>حد الرسائل/ساعة<input type="number" min="1" max="500" value={settings.public_rate_limit_per_hour||30} onChange={e=>setSettings({...settings,public_rate_limit_per_hour:Number(e.target.value)})}/></label><label>حد الرسائل/يوم<input type="number" min="1" max="2000" value={settings.public_daily_limit||120} onChange={e=>setSettings({...settings,public_daily_limit:Number(e.target.value)})}/></label><label>ملاحظة النظام<textarea rows="4" value={settings.system_note||''} onChange={e=>setSettings({...settings,system_note:e.target.value})}/></label></div><div className="control-row"><label className="switch-row"><input type="checkbox" checked={!!settings.public_chat_enabled} onChange={e=>setSettings({...settings,public_chat_enabled:e.target.checked})}/><span><b>فتح التطبيق العام</b><small>يسمح للناس بالدردشة بلا حساب</small></span></label><label className="switch-row"><input type="checkbox" checked={!!settings.public_training_enabled} onChange={e=>setSettings({...settings,public_training_enabled:e.target.checked})}/><span><b>استخدام المحادثات كمرشحي تدريب</b><small>مع تنبيه واضح للمستخدمين</small></span></label><label className="switch-row"><input type="checkbox" checked={!!settings.install_enabled} onChange={e=>setSettings({...settings,install_enabled:e.target.checked})}/><span><b>السماح بتثبيت التطبيق</b><small>PWA على الهاتف والحاسوب</small></span></label><label className="switch-row"><input type="checkbox" checked={!!settings.public_web_search_enabled} onChange={e=>setSettings({...settings,public_web_search_enabled:e.target.checked})}/><span><b>بحث الويب للمستخدمين</b><small>قد يزيد التكلفة، لذلك مغلق افتراضيًا</small></span></label><label className="switch-row"><input type="checkbox" checked={!!settings.auto_learning} onChange={e=>setSettings({...settings,auto_learning:e.target.checked})}/><span><b>التعلم التلقائي</b><small>حلقات التعلم المجدولة</small></span></label><label className="switch-row"><input type="checkbox" checked={!!settings.allow_paid_external} onChange={e=>setSettings({...settings,allow_paid_external:e.target.checked})}/><span><b>السماح بنماذج خارجية مدفوعة</b><small>مغلق افتراضيًا</small></span></label><label className="switch-row"><input type="checkbox" checked={!!settings.allow_paid_gpu} onChange={e=>setSettings({...settings,allow_paid_gpu:e.target.checked})}/><span><b>السماح بـ GPU مدفوع</b><small>لا يبدأ تلقائيًا عند إغلاقه</small></span></label></div><button className="primary-btn fit" onClick={saveSettings}>حفظ كل الإعدادات</button></section>}
  </main></div>
}
